name: Data Update

on:
  schedule:
    - cron: "0 6 */2 * *" #every 2 days
  workflow_dispatch:

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # set env
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: install python packages
      run: |
        cd code
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run Notebook
    - name: Run Jupyter Notebook
      run: |
        cd code
        jupyter nbconvert --to notebook --execute scraping.ipynb

    - name: GitHub Pages Publish
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "prediction result published"
        commit_options: '--no-verify --signoff'
        file_pattern: './*'
        repository: .
        status_options: '--untracked-files=no'
        skip_dirty_check: true
        skip_fetch: true
        skip_checkout: true
        push_options: '--force'
